import AOS from "aos";
import Head from "next/head";
import { useEffect } from "react";

import "aos/dist/aos.css";
import { useRouter } from "next/router";
import { Provider } from "react-redux";
import store  from "../backend/store/store";
import "../styles/globals.css";
import "../styles/loader.css";
import "../styles/selectbox.css";
function MyApp({ Component, pageProps }) {
  useEffect(() => {
    AOS.init();
  }, []);
  const location = useRouter();
  useEffect(() => {
    if (location.pathname === "/home-two") {
      document.body.classList.add("home-two");
    } else if (location.pathname === "/home-four") {
      document.body.classList.add("home-four");
    } else if (location.pathname === "/") {
      document.body.classList.remove("home-two");
      document.body.classList.add("home-one");
    }
    document.body.classList.add("home-one");
    return () => {
      document.body.classList.remove("home-two");
      document.body.classList.remove("home-four");
      document.body.classList.add("home-one");
    };
  }, [location.pathname]);
  return (
    <>
      <Provider store={store}>
        {/* <Provider store={store}> */}
        <Head>
          <title>NBTI Commerce</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favico.svg" />
        </Head>
        <Component {...pageProps} />
      </Provider>
    </>
  );
}

export default MyApp;
